// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	//r.GET("/ping", handler.Ping)

	// your code ...
	r.Static("/static", "./public")

	//利用hertz-jwt 进行jWT认证 参考：https://www.cnblogs.com/YLTFY1998/p/16898513.html
	//auth := r.Group("", mw.JwtMiddleware.MiddlewareFunc())
	//auth.GET("/refresh_token", mw.JwtMiddleware.RefreshHandler)
	//auth.GET("/ping", handler.Ping)
	//
	//auth.POST("/douyin/publish/action/", controller.Publish)

}
