// Code generated by hertz generator.

package main

import (
	"DY_BAT/cmd/api/biz/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// hertz server
	h := server.Default()

	// middleware
	rpc.InitUser()
	rpc.InitFavorite()
	register(h)
	h.Spin()
}
