// Code generated by Kitex v0.4.4. DO NOT EDIT.

package apiservice

import (
	api "DY_BAT/cmd/favorite/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserRegister(ctx context.Context, req *api.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *api.DouyinUserRegisterResponse, err error)
	UserLogin(ctx context.Context, req *api.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *api.DouyinUserLoginResponse, err error)
	UserInfo(ctx context.Context, req *api.Douyin_User_Request, callOptions ...callopt.Option) (r *api.DouyinUserResponse, err error)
	FavoriteAction(ctx context.Context, req *api.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *api.DouyinFavoriteActionResponse, err error)
	FavoriteList(ctx context.Context, req *api.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *api.DouyinFavoriteListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kApiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kApiServiceClient struct {
	*kClient
}

func (p *kApiServiceClient) UserRegister(ctx context.Context, req *api.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *api.DouyinUserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRegister(ctx, req)
}

func (p *kApiServiceClient) UserLogin(ctx context.Context, req *api.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *api.DouyinUserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogin(ctx, req)
}

func (p *kApiServiceClient) UserInfo(ctx context.Context, req *api.Douyin_User_Request, callOptions ...callopt.Option) (r *api.DouyinUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserInfo(ctx, req)
}

func (p *kApiServiceClient) FavoriteAction(ctx context.Context, req *api.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *api.DouyinFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, req)
}

func (p *kApiServiceClient) FavoriteList(ctx context.Context, req *api.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *api.DouyinFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteList(ctx, req)
}
